# Marburg Open Educational Resources
#
# This config file is meant for settings that affect the whole course space.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server
# process.

# Site settings 
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Adjust title etc. Depending on serving the site on GitHub or OER, different
# url and baseurl settings have to be used.


##### URL #####################################################################
# Serve on OER
#url: "https://ilias.uni-marburg.de"
#baseurl: "/data/UNIMR/lm_data/lm_2092236/"


# Serve on GitHub
url: https://geomoer.github.io/
baseurl: "/moer-mpg-gis/"

##### Title ###################################################################
title: Lab of Environmental Informatics
name: &name "Lab of Environmental Informatics" # &name is a YAML anchor which can be *referenced later
email: reudenbach@geo.uni-marburg.de
description: >- # this means to ignore newlines until next item
  course course-materials geography remote-sensing marburg-open-educational-resource 
  physical-geography environmental-science nature-conservation r

##### Social Sharing ##########################################################
twitter:
  username         : &twitter "creuden"

##### Lecturer settings #######################################################
author:
  name             : "Christoph Reudenbach"
  avatar           : "/assets/images/creudenbach.jpg"
  bio              : "Marburg University"
  location         : "Marburg, DE"
  email            : "reudenbach@geo.uni-marburg.de"
  uri              : "https://www.uni-marburg.de/fb19/personal/mitarbeiter/reudenbachc/index.html"
  home             : "https://gis-ma.org"
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           : "https://www.flickr.com/environmentalinformatics-marburg/"
  facebook         : "https://www.facebook.com/GeographieMarburg/"
  foursquare       :
  github           : "GeoMOER"
  gitlab           :
  google_plus      :
  keybase          :
  instagram        : 
  lastfm           :
  linkedin         :
  pinterest        :
  soundcloud       :
  stackoverflow    : 
  steam            :
  tumblr           :
  twitter          : "https://twitter.com/creuden"
  vine             :
  weibo            :
  xing             :
  youtube          : "https://www.youtube.com/channel/UCGiwSv5KYjsNXl6-nZq0SDA"


##### Site configuration ######################################################
title_separator: "|"
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
# theme: minima
remote_theme: "GeoMOER/moer-jekyll-theme"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
auto_ids: true

# Default Settings
collections_dir: units

# Includes
include:
  - _pages

# Collections
collections:
  examples:
    output: true
    permalink: /:collection/:title.html
  unit00:
    output: true
    permalink: /:collection/:title.html    
  unit01:
    output: true
    permalink: /:collection/:title.html
  unit02:
    output: true
    permalink: /:collection/:title.html
  unit03:
    output: true
    permalink: /:collection/:title.html
  unit04:
    output: true
    permalink: /:collection/:title.html
  unit05:
    output: true
    permalink: /:collection/:title.html
  spotlight:
    output: true
    permalink: /:collection/:title.html

# Default settings
defaults:
  # examples
  - scope:
      path: ""
      type: examples
    values:
      category: "examples"
      tags: "Examples"
      layout: single
      sidebar:
        nav: "units" 
  # unit01
  - scope:
      path: ""
      type: unit00
    values:
      category: "Some Formalities"
      tags: "Unit|01"
      layout: single
      sidebar:
        nav: "units" 
      toc: true
      toc_label: On this page      
        
  # unit01
  - scope:
      path: ""
      type: unit01
    values:
      category: "Questions & Answers"
      tags: "Unit|01"
      layout: single
      sidebar:
        nav: "units" 
      toc: true
      toc_label: On this page      
  # unit02
  - scope:
      path: ""
      type: unit02
    values:
      category: "Spatial Modelling  Concepts"
      tags: "Unit|02"
      layout: single
      sidebar:
        nav: "units" 
  # unit03
  - scope:
      path: ""
      type: unit03
    values:
      category: "Project 1: Touching the tree"
      tags: "Unit|03"
      layout: single
      sidebar:
        nav: "units" 
  # unit04
  - scope:
      path: ""
      type: unit04
    values:
      category: "Project 2: Competition and Biodiversity"
      tags: "Unit|04"
      layout: single
      sidebar:
        nav: "units" 
  # unit05
  - scope:
      path: ""
      type: unit05
    values:
      category: "Spotlights"
      tags: "Unit|05"
      layout: single
      sidebar:
        nav: "units" 
  # pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      sidebar:
        nav: "docs"         

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-admin
  - jekyll-paginate
  - jekyll-gist
  - jemoji
  - jekyll-include-cache
  - jekyll-algolia

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


theme: jekyll-theme-minimal
